
os:
  - linux
sudo: false
before_script:
  - cd $HOME
  - git clone https://github.com/flutter/flutter.git --depth 1
  - cd -
  - export PATH="$PATH:$HOME/flutter/bin"
  - flutter doctor
jobs:
  include:
    - state: Format
      script: flutter format --set-exit-if-changed -n lib
    - state: Test
      script: flutter test
cache:
  directories:
    - $HOME/.pub-cache
