
os:
  - linux
sudo: false
before_script:
  - cd $HOME
  - git clone https://github.com/flutter/flutter.git
  - cd -
  - export $PATH="$PATH:$HOME/flutter/bin"
  - flutter doctor
jobs:
  include:
    - state: Format
      script: ./check-format.sh
    - state: Test
      script: flutter test
cache:
  directories:
    - $HOME/.pub-cache
